name: time_apk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  hijri: ^3.0.0      # Buat konversi Masehi ke Hijriah
  intl: ^0.19.0      # Buat formatting tanggal Masehi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true